version: '3.9'

services: 
  database:
    image: mongo:6.0.2
    container_name: database-mongo
    hostname: database-mongo
    restart: always 
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - '27017:27017'
    volumes: 
      - mongodb_data_container:/data/db

  
volumes: 
  mongodb_data_container:
